//! Phase 26: MarkovJunior 3D Bevy Rendering
//!
//! Demonstrates loading a MarkovJunior XML model, running it in 3D,
//! converting to VoxelWorld, and rendering with Bevy's deferred lighting.
//!
//! Run with: `cargo run --example p26_markov_bevy_3d`
//!
//! Expected output: `screenshots/p26_markov_bevy_3d.png`
//! - 3D voxel structure generated by MarkovJunior (Apartemazements)
//! - Deferred lighting with shadows
//! - Camera looking at the structure from an angle

use bevy::prelude::*;
use std::path::Path;
use studio_core::markov_junior::{MjPalette, Model};
use studio_core::{VoxelWorldApp, WorldSource};

fn main() {
    println!("Phase 26: MarkovJunior 3D Bevy Rendering");

    // Load the Apartemazements model - generates interesting 3D apartment buildings
    let xml_path = Path::new("MarkovJunior/models/Apartemazements.xml");
    let size = 8; // Apartemazements works well at 8x8x8
    let mut model =
        Model::load_with_size(xml_path, size, size, size).expect("Failed to load Apartemazements");

    println!(
        "Grid size: {}x{}x{}",
        model.grid().mx,
        model.grid().my,
        model.grid().mz
    );

    // Run the model with a fixed seed for reproducibility
    let seed = 42;
    let max_steps = 50000; // Apartemazements needs more steps
    let steps = model.run(seed, max_steps);
    let grid = model.grid();

    let nonzero = grid.count_nonzero();
    let total = grid.mx * grid.my * grid.mz;
    println!(
        "Generation complete: {} steps, {} voxels ({:.1}% filled)",
        steps,
        nonzero,
        100.0 * nonzero as f64 / total as f64
    );

    // Convert to VoxelWorld using palette that matches grid's characters
    let palette = MjPalette::from_grid(grid);
    let world = grid.to_voxel_world(&palette);

    let voxel_count: usize = world.iter_chunks().map(|(_, c)| c.count()).sum();
    println!("VoxelWorld contains {} voxels", voxel_count);

    // Run with VoxelWorldApp - deferred rendering with shadows
    VoxelWorldApp::new("Phase 26: MarkovJunior 3D")
        .with_world(WorldSource::World(world))
        .with_resolution(1280, 720)
        .with_clear_color(Color::srgb(0.1, 0.1, 0.15))
        .with_deferred(true) // Use deferred rendering for better lighting
        .with_greedy_meshing(true)
        .with_camera_angle(45.0, 30.0)
        .with_zoom(0.6) // Zoom out to see the full structure
        .with_screenshot("screenshots/p26_markov_bevy_3d.png")
        .run();
}
