//! Phase 26: MarkovJunior 3D Bevy Rendering
//!
//! Demonstrates loading a MarkovJunior XML model, running it in 3D,
//! converting to VoxelWorld, and rendering with Bevy's deferred lighting.
//!
//! Run with: `cargo run --example p26_markov_bevy_3d`
//!
//! Expected output: `screenshots/p26_markov_bevy_3d.png`
//! - 3D voxel structure generated by MarkovJunior
//! - Deferred lighting with shadows
//! - Camera looking at the structure from an angle

use bevy::prelude::*;
use studio_core::markov_junior::{MjPalette, Model};
use studio_core::{VoxelWorldApp, WorldSource};

fn main() {
    println!("Phase 26: MarkovJunior 3D Bevy Rendering");

    // Create a simple 3D growth model programmatically
    // Uses B→W rule which can match anywhere in 3D (not just along one axis)
    // with origin=true to start from center
    let xml = r#"<one values="BW" origin="True" in="B" out="W"/>"#;

    let size = 16;
    let mut model =
        Model::load_str(xml, size, size, size).expect("Failed to create 3D growth model");

    println!(
        "Grid size: {}x{}x{}",
        model.grid().mx,
        model.grid().my,
        model.grid().mz
    );

    // Run the model with a fixed seed for reproducibility
    // Limit steps to create an interesting partial fill (not complete cube)
    let seed = 12345;
    let max_steps = 2000; // Stop before complete fill for interesting shape
    let steps = model.run(seed, max_steps);
    let grid = model.grid();

    let nonzero = grid.count_nonzero();
    let total = grid.mx * grid.my * grid.mz;
    println!(
        "Generation complete: {} steps, {} voxels ({:.1}% filled)",
        steps,
        nonzero,
        100.0 * nonzero as f64 / total as f64
    );

    // Convert to VoxelWorld using palette that matches grid's characters
    let palette = MjPalette::from_grid(grid);
    let world = grid.to_voxel_world(&palette);

    let voxel_count: usize = world.iter_chunks().map(|(_, c)| c.count()).sum();
    println!("VoxelWorld contains {} voxels", voxel_count);

    // Run with VoxelWorldApp - deferred rendering with shadows
    VoxelWorldApp::new("Phase 26: MarkovJunior 3D")
        .with_world(WorldSource::World(world))
        .with_resolution(1280, 720)
        .with_clear_color(Color::srgb(0.1, 0.1, 0.15))
        .with_deferred(true) // Use deferred rendering for better lighting
        .with_greedy_meshing(true)
        .with_camera_angle(45.0, 30.0)
        .with_zoom(0.6) // Zoom out to see the full structure
        .with_screenshot("screenshots/p26_markov_bevy_3d.png")
        .run();
}
