//! Phase 27: MarkovJunior ImGui Integration Test
//!
//! Tests the Phase 3.3 and 3.6 features:
//! - ImGui PNG save button
//! - Live 3D voxel rendering from Lua
//!
//! Run with: `cargo run --example p27_markov_imgui`
//!
//! Expected output: `screenshots/p27_markov_imgui.png`
//! - 3D voxel structure generated by MarkovJunior (Apartemazements)

use bevy::prelude::*;
use std::path::Path;
use studio_core::markov_junior::{MjPalette, Model};
use studio_core::{VoxelWorldApp, WorldSource};

fn main() {
    println!("Phase 27: MarkovJunior ImGui Integration Test");

    // Load the Apartemazements model - generates interesting 3D apartment buildings
    let xml_path = Path::new("MarkovJunior/models/Apartemazements.xml");
    let size = 8; // Apartemazements works well at 8x8x8
    let mut model =
        Model::load_with_size(xml_path, size, size, size).expect("Failed to load Apartemazements");

    println!(
        "Grid size: {}x{}x{}",
        model.grid().mx,
        model.grid().my,
        model.grid().mz
    );

    // Run the model with a fixed seed for reproducibility
    let seed = 42;
    let max_steps = 50000; // Apartemazements needs more steps
    let steps = model.run(seed, max_steps);
    let grid = model.grid();

    let nonzero = grid.count_nonzero();
    let total = grid.mx * grid.my * grid.mz;
    println!(
        "Generation complete: {} steps, {} voxels ({:.1}% filled)",
        steps,
        nonzero,
        100.0 * nonzero as f64 / total as f64
    );

    // Test PNG rendering (Phase 3.3)
    use studio_core::markov_junior::render::render_to_png;

    let png_path = Path::new("screenshots/p27_markov_imgui_test.png");
    render_to_png(grid, png_path, 8).expect("Failed to render PNG");
    println!("PNG saved to: {}", png_path.display());

    // Convert to VoxelWorld using palette
    let palette = MjPalette::from_grid(grid);
    let world = grid.to_voxel_world(&palette);

    println!("VoxelWorld contains {} voxels", world.total_voxel_count());

    // Run with VoxelWorldApp
    VoxelWorldApp::new("Phase 27: MarkovJunior ImGui Test")
        .with_world(WorldSource::World(world))
        .with_resolution(1280, 720)
        .with_clear_color(Color::srgb(0.1, 0.1, 0.15))
        .with_deferred(true)
        .with_greedy_meshing(true)
        .with_camera_angle(45.0, 30.0)
        .with_zoom(0.6)
        .with_screenshot("screenshots/p27_markov_imgui.png")
        .run();
}
